version: '3'

services:
  nexus-retail:
    build: .
    container_name: nexus-retail-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
